### PR TITLE
add cors header for new country data.json files

### PR DESCRIPTION
**Pull request by ngottlieb**

### CODE REVIEW

**Comment by ngottlieb** [comment]
resolves #423

**Comment by alex** [comment]
I'm pretty sure Apache supports a file regexp for these things, which would save the trouble and duplication.

**Comment by drwestco** [comment]
Regex suggestion is a good one. https://www.askapache.com/htaccess/using-filesmatch-and-files-in-htaccess/

**Comment by ngottlieb** [comment]
copy that, was blocking what I was working on (slightly) so I just mimicked what was already there but I will update this PR with regex instead

**Comment by ngottlieb** [comment]
@drwestco updated

**Pull request merged**
