### PR TITLE
Update Text for Large Donations

### PR DESCRIPTION
**Pull request by dhruv4**
References #315.

Updates the text as Rachel specified.

### CODE REVIEW

**Comment by graemer** [comment]
@dhruv4, can you also update this within the /i18n/en.json and /i18n/fr-fr.json assets?

**Comment by dhruv4** [comment]
Oops that was dumb of me. Pushed an update and asked a friend to review Google's French. Her take: "Google is wack".

**Comment by nburt** [comment]
@dhruv4 Any chance your friend would want to help out with French translations? Also fyi we should only be pushing en.json files going forward and then all language translations will happen within Smartling and then will be pushed here as PRs

**Comment by dhruv4** [comment]
@nburt I'll ask and follow up with you via Slack! Sorry about the json mixup. I must have totally missed that since yesterday. Thanks for clarifying :)

**Comment by nburt** [comment]
> @nburt I'll ask and follow up with you via Slack! Sorry about the json mixup. I must have totally missed that since yesterday. Thanks for clarifying :)

All good, I just set things up today but haven't fully documented and explained it to everyone yet

**Pull request merged**
