### PR TITLE
Resolves #726: add the ability to filter by accepted items + org types

### LINKED ISSUE #726: Add query param to URL to filter map by the items the org is accepting for donation
add a `?accepting=homemade%20masks,3D-printed%20face%20shields` query param for use with embeds

- The map / locations list should be filtered
- Multiple accepted items can be passed with a comma separator
- The filters multi select should be updated to match the query param
- Document new filter in [wiki](https://github.com/findthemasks/findthemasks/wiki/Embedding-%23findthemasks-donation-sites-page)

### PR DESCRIPTION
**Pull request by nburt**
Updated wiki too: https://github.com/findthemasks/findthemasks/wiki/Embedding-%23findthemasks-donation-sites-page

example: https://findthemasks-filter-by--bgduqg.herokuapp.com/?accepting=homemade%20masks,gloves&orgType=hospital,Doctor%27s%20Office

### CODE REVIEW

**Comment by linderr** [comment]
whoa!!! This is so cool!!!

**Comment by linderr** [comment]
@nburt not sure if it's just a test-site thing but homemade masks shows up twice in your filter items menu. Please check

**Comment by linderr** [comment]
AlsooOOoo how hard would it be to allow these same params for the /maker map? they have more items and not every makerspace produces all the items so this is SO useful!!! thank you!

**Comment by saikatbhadra** [comment]
It looks like we have two articles on embeds: https://github.com/findthemasks/findthemasks/wiki/Embedding-%23findthemasks-donation-sites-page
https://github.com/findthemasks/findthemasks#embeddable-widget-of-donation-sites

Is there a reason to have both? what is the difference?

**Comment by linderr** [comment]
@saikatbhadra I think the second one is the part of the full README.md file?
While the Wiki pages are heavily used by non-devs like me, the comms girls, Julia to refer to when we work with embed partners. I have literally never read the Read Me :) Code tab is scary 👍

**Comment by awong-dev** [comment]
The Homemade Masks showing up twice is an existing bug. Merging this and filing a new one.

**Pull request merged**
