### PR TITLE
Favicon and meta in <head>

### PR DESCRIPTION
**Pull request by cjimmy**
* Moved favicons to subfolder, adjusted *.html accordingly.
* added <meta> og tags for unfurl preview
* added canonical url in head

### CODE REVIEW

**Comment by graemer** [comment]
@cjimmy - Is it not possible to move the french-specific strings within the meta tags to https://github.com/findthemasks/findthemasks/blob/master/public/i18n.js? (you'd likely need to extend a bit)

**Comment by cjimmy** [comment]
Good question. After looking into it, I suspect we can't if we want crawlers to parse it correctly. Most crawlers take the html as it is without rendering the js. Google does render js when it crawls, but I don't know if jquery.i18n will correctly localize the head tags in time. Facebook's crawler doesn't even render js even though they own React and are responsible for single-page apps being popular. It's something we should test, especially if we plan to internationalize more. For right now, my rec is to hardcode it for SEO sake, and test how if it works in i18n.js.

**Comment by graemer** [comment]
Yeah, I suspect we'll need to move to server-side rendered if we want to do this...

**Comment by awong-dev** [comment]
Don't forget we have a php backend

**Pull request merged**
