### PR TITLE
Feature/faq page ux2

### LINKED ISSUE #664: [v2] Apply UX/UI on FAQ page
FAQ skeleton + content is up.

Just needs final touches as per 'dev ready' version on Figma :)

### PR DESCRIPTION
**Pull request by ngottlieb**
resolves #664

### CODE REVIEW

**Comment by linderr** [comment]
First of all. Amazing and thank you for doing this work.

**Comment by linderr** [comment]
Going through now.
500+ item needs to be stylized by "+" CSS
image

**Comment by ngottlieb** [comment]
> Going through now.
> 500+ item needs to be stylized by "+" CSS
> image

just an issue for Canada, pushed a fix

**Comment by linderr** [comment]
@ngottlieb please add on the right hand column
Partnerships/Collaborators: partners@findthemasks.com (goes to Julia (US) & CA gmail)

**Comment by saikatbhadra** [comment]
Great work 🚀🚀

**Pull request merged**
