### PR TITLE
ensure logo in nav brand is clickable

### LINKED ISSUE #827: Change Mouse hover on top-left Logo from Select to Hand [FTM & Makers]
Users need a clear way to navigate back to the main map from subpages. Currently that is not clear on both FTM and FTMakers.

**Context**
When you are on a Subpage and want/need to navigate back to the map, the UX is to click on the top-left logo to go back to the map.

Right now, the mouse hover is a Select Tool (capital I-looking thing) which does not clearly indicate the top-left logo is clickable. Also the logo text becomes grey upon hover, further confusing whether the logo is clickable or not.

**Asks:**
- change the mouse hover over the logo from Select to Hand on both findthemasks.com and findthemakers.com
- change the hover text to be not-grey

### PR DESCRIPTION
**Pull request by ngottlieb**
resolves #827

### CODE REVIEW

**Comment by linderr** [comment]
Nice. And I love how you made the logo bigger too! Much more striking and legit.

**Comment by ngottlieb** [comment]
Hahah, that may have been a small accident, I was trying to replicate it as is...

**Comment by linderr** [comment]
hahah well, as Bob Ross says --- life is all about happy little accidents - good job

**Comment by linderr** [comment]
@ngottlieb oops I just saw this on Makers. Masks is fine:
image

**Comment by ngottlieb** [comment]
it's a caching issue, the markup has updated (HTML) but the CSS has not. if you're on a mac/chrome, press "command + shift + r" and it'll force it to reload

**Comment by linderr** [comment]
Yessir. Doh!
image

**Pull request merged**
