### PR TITLE
Reset button bug

### PR DESCRIPTION
**Pull request by NickB64**
Resetting the map will now uncheck the "Makers" filter under datasets. Issue #850.

### CODE REVIEW

**Comment by ngottlieb** [comment]
@NickB64 can you cherry-pick the commit into a new PR? This accidentally included top of two other commits (that haven't *quite* been merged yet)

**Comment by ngottlieb** [comment]
Follow-up point -- the goal is to potentially have more datasets in that interface where the makers box is. So there's at least one additional piece to make it more versatile:

- add a class to the container and call this for *all* checkboxes in it

**Comment by awong-dev** [comment]
What's the next steps on this PR?

**Comment by ngottlieb** [comment]
cherry-picked to #1054

**Pull request closed without merging**
