### PR TITLE
add filters to makers for products + capabilities

### PR DESCRIPTION
**Pull request by nburt**

### CODE REVIEW

**Comment by linderr** [comment]
Awesome work! Great choice on the two base filter items.

Can the filter options be in alphabetical order?
Categories: 3D printing, A B C, Other
Products: ABC, Other ?

**Comment by nburt** [comment]
> Awesome work! Great choice on the two base filter items.
> 
> Can the filter options be in alphabetical order?
> Categories: 3D printing, A B C, Other
> Product Type: ABC, Other ?

Unfortunately we can't without a substantial amount of work since it'll need to work across all languages. I agree that's better behavior but we should do it in a separate issue since this isn't what we do for find the masks either.

**Comment by linderr** [comment]
You have some mega fan love from Claire C on #makers-ftm from Nation of Makers She also asked for "Other" to be dropped to the bottom --- maybe this is a more appropriate ask; I'll midnight issue that ABC stuff --- thanks, Nate! This is great!

**Comment by awong-dev** [comment]
An actual use of reduce()!!!! <3. 

Very nicely done :)

**Pull request merged**
