### PR TITLE
update fr strings + load language for map

### PR DESCRIPTION
**Pull request by nburt**

### CODE REVIEW

**Comment by nburt** [comment]
Still don't have all French translations but wanted to get this up

**Comment by nburt** [comment]
- [ ] Need to be able to swap form to French when country set to fr: https://drive.google.com/open?id=1lZ1zepAjRFu4GZyP9yW_Wfas3mUChcZc0Z8Y46eI3M8

**Comment by patricknelson** [comment]
Inspiration from PR #258? Thanks we needed this!

**Comment by patricknelson** [comment]
Deleted my last comment in shame! 🤐

**Pull request merged**
