### PR TITLE
Add line breaks between entries

### PR DESCRIPTION
**Pull request by saikatbhadra**
This is just a stopgap until we get designs. I dislike CSS so if anyone has better styling to recommend please feel free to add.

How it looks on mobile:

Screen Shot 2020-04-08 at 12 06 02 PM

### CODE REVIEW

**Comment by drwestco** [comment]
Why? What problem are you trying to solve? Are the bold titles of each entry not sufficient?

**Comment by saikatbhadra** [comment]
We have had several folks complain that the entries flow into each other. So yea there is not enough visual cues to tell where one entry ends and one entry starts.

**Comment by saikatbhadra** [comment]
@ngottlieb has suggested zebra striping which is probably a better approach

**Comment by drwestco** [comment]
If you want to change this to the indent method discussed in #dev, the two rules I used were:

```
.location > * {
  padding-left: 2rem;
}

/* Added to end of existing rule */
.locations-list h4 {
  padding-left: 0;
}

**Comment by saikatbhadra** [comment]
I put in the indentation fix that @drwestco suggested, thanks!

**Pull request closed without merging**
