### PR TITLE
1049 Embed font size adjustment & add font mixin

### PR DESCRIPTION
**Pull request by eikhunter**

### CODE REVIEW

**Comment by ngottlieb** [comment]
fine by me

**Comment by tobiasdeml** [comment]
Not trying to be nitpicky, but is this resolved? The font of the list still looks pretty big on my embeds / takes up a good deal of space. ;-)

**Comment by eikhunter** [comment]
From my understanding, it was "responsiveness adjustments" which usually sits within the realm of tablet and mobile, so I adjusted the font sizes of these accordingly and not the desktop view, i'll adjust this next week, thanks.

**Comment by tobiasdeml** [comment]
Thanks so much Eik!

Toby

--

Tobias Deml
+1 310.350.5384

Co-Founder & Producer/DP
www.prodigium.pictures
1601 Vine Street, Hollywood, 90028 CA

Co-Founder & Editor in Chief
www.cinemaofchange.com

**Pull request merged**
